Repository crossplane/upjet, pull requests merged in 2022-10, with the labels that each got.

#111 docs: add contribution guide and edit outdated parts of README
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  NOTICE
  README.md
  docs/README.md
  docs/add-new-resource-long.md
  docs/add-new-resource-short.md
  docs/generating-a-provider.md
  go.mod
  go.sum
  pkg/config/provider.go
  pkg/controller/options.go
  pkg/pipeline/run.go
  pkg/terraform/provider_runner_test.go
  pkg/types/comments/comment.go
  pkg/types/comments/comment_test.go
  pkg/types/conversion/tfjson/tfjson.go
  pkg/types/field.go
  pkg/types/markers/options.go
  pkg/types/markers/terrajet.go
  pkg/types/markers/terrajet_test.go
Labels: size/L

#112 Add PollInterval to controller setup functions
  pkg/pipeline/templates/controller.go.tmpl
Labels: size/XS

#115 Update new provider documentation
  .github/workflows/ci.yml
  cmd/scraper/main.go
  docs/generating-a-provider.md
  pkg/config/provider.go
  pkg/registry/meta.go
Labels: size/L

#117 Fixes in add-new-resource-short.md doc
  docs/add-new-resource-short.md
Labels: size/S
