Repository crossplane/upjet, pull requests merged in 2022-11, with the labels that each got.

#123 docs: add preferred provider repository naming
  docs/generating-a-provider.md
Labels: size/XS, community

#137 Add config.Provider.GetSkippedResourceNames
  pkg/config/provider.go
Labels: size/S

#138 Handle sensitive input maps via SecretReference
  pkg/resource/sensitive.go
  pkg/resource/sensitive_test.go
  pkg/types/builder.go
  pkg/types/field.go
  pkg/types/reference.go
Labels: size/L

#133 Add terrajet-to-upjet migration guide
  docs/migrating-from-terrajet-to-upjet.md
Labels: size/L
